"""add cascade delete to OrderItem order_id field

Revision ID: 11ad271f8e06
Revises: f9a99ea8a25c
Create Date: 2025-05-17 19:19:41.853991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11ad271f8e06'
down_revision = 'f9a99ea8a25c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_item', schema=None) as batch_op:
        batch_op.drop_constraint('order_item_order_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'order', ['order_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_item', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('order_item_order_id_fkey', 'order', ['order_id'], ['id'])

    # ### end Alembic commands ###
